services:
  web:
    container_name: laravel-web
    build:
      context: .
      dockerfile: docker/dev/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    user: "1000:1000"
    links:
      - php

  php:
    container_name: laravel-php
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
    volumes:
      - ./:/app
#      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    user: "1000:1000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=1
      - XDEBUG_MODE=coverage,debug
      - DBGP_IDEKEY=PHPSTORM

  db:
    container_name: laravel-db
    image: mysql:9.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: listaco
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
