sha: image-sha

mysql:
  name: listaco-backend-mysql
  replicas: 1
  servicePort: 3306
  database: listaco
  volume:
    name: listaco-backend-mysql-storage
    mountPath: /var/lib/mysql
    class: nfs-client
    pvc:
      name: listaco-backend-mysql-volume-claim
    requests:
      storage: 500Mi
  container:
    image: mysql:9.1.0
    port: 3306
  secret:
      name: mysql-credentials
      keys:
        username: user
        password: password

nginx:
  name: listaco-backend-nginx
  replicas: 1
  servicePort: 80
  container:
    image: ghcr.io/romeronet/listaco-backend/nginx
    port: 80
  ingress:
    host: dev-listaco.romeronet.es
    tlsSecret: tls
    path: /api

php:
  name: listaco-backend-php
  replicas: 1
  servicePort: 9000
  container:
    image: ghcr.io/romeronet/listaco-backend/php
    port: 9000
  app:
    env: dev
    debug: 1
